# Generated by Django 6.0.2 on 2026-05-22 10:52

import catalogue.encryption
import catalogue.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColorClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название классификации цвета')),
            ],
            options={
                'verbose_name': 'Классификация цвета',
                'verbose_name_plural': 'Классификации цветов',
                'db_table': 'color_classification',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CreativeCollective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название творческого коллектива')),
            ],
            options={
                'verbose_name': 'Творческий коллектив',
                'verbose_name_plural': 'Творческие коллективы',
                'db_table': 'creative_collective',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский'), ('Мальчик', 'Мальчик'), ('Девочка', 'Девочка'), ('Унисекс', 'Унисекс')], max_length=7, unique=True, verbose_name='Пол')),
            ],
            options={
                'verbose_name': 'Пол',
                'verbose_name_plural': 'Пол',
                'db_table': 'gender',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GrantPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=catalogue.models.generate_uuid, editable=False, max_length=36, verbose_name='UUID')),
                ('last_name', catalogue.encryption.EncryptedCharField(max_length=900, verbose_name='Фамилия')),
                ('first_name', catalogue.encryption.EncryptedCharField(max_length=900, verbose_name='Имя')),
                ('middle_name', catalogue.encryption.EncryptedCharField(blank=True, max_length=900, null=True, verbose_name='Отчество')),
                ('phone_number', catalogue.encryption.EncryptedCharField(blank=True, max_length=450, null=True, verbose_name='Номер телефона')),
                ('email', catalogue.encryption.EncryptedCharField(blank=True, max_length=2286, null=True, verbose_name='Электронная почта')),
            ],
            options={
                'verbose_name': 'Ответственное лицо',
                'verbose_name_plural': 'Ответственные лица',
                'db_table': 'grant_person',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='HoldPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Название места хранения')),
                ('photo', models.ImageField(help_text='Загрузите фотографию места хранения', upload_to='hold_places/%Y/%m/', verbose_name='Фотография места хранения')),
            ],
            options={
                'verbose_name': 'Место хранения',
                'verbose_name_plural': 'Места хранения',
                'db_table': 'hold_place',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название материала')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
                'db_table': 'material',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaterialClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название классификации материала')),
            ],
            options={
                'verbose_name': 'Классификация материала',
                'verbose_name_plural': 'Классификации материалов',
                'db_table': 'material_classification',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Renter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=36, verbose_name='UUID')),
                ('last_name', catalogue.encryption.EncryptedCharField(max_length=900, verbose_name='Фамилия')),
                ('first_name', catalogue.encryption.EncryptedCharField(max_length=900, verbose_name='Имя')),
                ('middle_name', catalogue.encryption.EncryptedCharField(blank=True, max_length=900, null=True, verbose_name='Отчество')),
                ('phone_number', catalogue.encryption.EncryptedCharField(blank=True, max_length=450, null=True, verbose_name='Номер телефона')),
                ('email', catalogue.encryption.EncryptedCharField(blank=True, max_length=2286, null=True, verbose_name='Электронная почта')),
            ],
            options={
                'verbose_name': 'Арендатор',
                'verbose_name_plural': 'Арендаторы',
                'db_table': 'renter',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='RentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Активна', 'Активна'), ('Завершена', 'Завершена'), ('Просрочена', 'Просрочена'), ('Отменена', 'Отменена'), ('В обработке', 'В обработке')], max_length=30, unique=True, verbose_name='Название статуса')),
            ],
            options={
                'verbose_name': 'Статус аренды',
                'verbose_name_plural': 'Статусы аренды',
                'db_table': 'rent_status',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RequestStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Новая', 'Новая'), ('В обработке', 'В обработке'), ('Одобрена', 'Одобрена'), ('Выполнена', 'Выполнена'), ('Отменена', 'Отменена')], max_length=50, unique=True, verbose_name='Название статуса')),
            ],
            options={
                'verbose_name': 'Статус заявки',
                'verbose_name_plural': 'Статусы заявок',
                'db_table': 'request_status',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Зима', 'Зима'), ('Весна', 'Весна'), ('Лето', 'Лето'), ('Осень', 'Осень'), ('Всесезонный', 'Всесезонный')], max_length=11, unique=True, verbose_name='Название сезона')),
            ],
            options={
                'verbose_name': 'Сезон',
                'verbose_name_plural': 'Сезоны',
                'db_table': 'season',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TicketStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Новая', 'Новая'), ('В работе', 'В работе'), ('Закрыта', 'Закрыта')], max_length=50, unique=True, verbose_name='Название статуса')),
            ],
            options={
                'verbose_name': 'Статус заявки поддержки',
                'verbose_name_plural': 'Статусы заявок поддержки',
                'db_table': 'ticket_status',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название цвета')),
                ('hex_code', models.CharField(blank=True, help_text='Формат: #RRGGBB', max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Введите корректный HEX код цвета (например, #FF5733)', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='HEX код цвета')),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colors', to='catalogue.colorclassification', verbose_name='Классификация цвета')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
                'db_table': 'color',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CostumeClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название классификации')),
                ('parent', models.ForeignKey(blank=True, help_text='Указывается в том случае, когда добавляемая классификация является подклассификацией. Например, драмматические постановки - подклассификация для театральных костюмов. Если указывается основная классификация - оставьте поле пустым.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalogue.costumeclassification', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Классификация костюма',
                'verbose_name_plural': 'Классификации костюмов',
                'db_table': 'costume_classification',
                'ordering': ['name'],
                'unique_together': {('name', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='Costume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название костюма')),
                ('inventory_code', models.CharField(help_text='Например, 00000000000001', max_length=14, unique=True, verbose_name='Инвентарный код')),
                ('description', models.CharField(blank=True, max_length=1024, verbose_name='Описание')),
                ('count', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество')),
                ('state', models.CharField(choices=[('Отличное', 'Отличное'), ('Хорошее', 'Хорошее'), ('Удовлетворительное', 'Удовлетворительное'), ('Требует ремонта', 'Требует ремонта'), ('Списан', 'Списан')], max_length=28, verbose_name='Состояние')),
                ('note', models.CharField(blank=True, max_length=256, verbose_name='Примечание')),
                ('rent_cost', models.DecimalField(decimal_places=2, default=500.0, help_text='Может быть указано вплоть до копеек', max_digits=8, verbose_name='Стоимость аренды за сутки')),
                ('year', models.PositiveIntegerField(blank=True, default=2026, null=True, verbose_name='Год ввода в эксплуатацию')),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='costumes', to='catalogue.costumeclassification', verbose_name='Классификация костюма')),
            ],
            options={
                'verbose_name': 'Костюм',
                'verbose_name_plural': 'Костюмы',
                'db_table': 'costume',
                'ordering': ['inventory_code'],
            },
        ),
        migrations.CreateModel(
            name='CostumeColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.color', verbose_name='Цвет')),
                ('costume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.costume', verbose_name='Костюм')),
            ],
            options={
                'verbose_name': 'Цвет костюма',
                'verbose_name_plural': 'Цвета костюмов',
                'db_table': 'costume_color',
                'unique_together': {('costume', 'color')},
            },
        ),
        migrations.AddField(
            model_name='costume',
            name='colors',
            field=models.ManyToManyField(related_name='costumes', through='catalogue.CostumeColor', to='catalogue.color', verbose_name='Цвета'),
        ),
        migrations.CreateModel(
            name='CostumePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='costumes_photo/%Y/%m/', verbose_name='Фотография костюма')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('costume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='catalogue.costume', verbose_name='Костюм')),
            ],
            options={
                'verbose_name': 'Фотография костюма',
                'verbose_name_plural': 'Фотографии костюмов',
                'db_table': 'costume_photo',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CostumeSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, unique=True, verbose_name='Обозначение размера')),
                ('min_age', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(150)], verbose_name='Минимальный возраст')),
                ('max_age', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(150)], verbose_name='Максимальный возраст')),
                ('is_child', models.BooleanField(verbose_name='Детский размер')),
            ],
            options={
                'verbose_name': 'Размер костюма',
                'verbose_name_plural': 'Размеры костюмов',
                'db_table': 'costume_size',
                'ordering': ['min_age', 'label'],
                'constraints': [models.CheckConstraint(condition=models.Q(('min_age__lte', models.F('max_age'))), name='min_age_lte_max_age'), models.CheckConstraint(condition=models.Q(('min_age__gte', 0), ('max_age__gte', 0)), name='ages_non_negative')],
            },
        ),
        migrations.AddField(
            model_name='costume',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='costumes', to='catalogue.costumesize', verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='costume',
            name='creative_collective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='costumes', to='catalogue.creativecollective', verbose_name='Творческий коллектив'),
        ),
        migrations.AddField(
            model_name='costume',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='costumes', to='catalogue.gender', verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='costume',
            name='grant_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='costumes', to='catalogue.grantperson', verbose_name='Ответственное лицо'),
        ),
        migrations.AddField(
            model_name='costume',
            name='hold_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='costumes', to='catalogue.holdplace', verbose_name='Место хранения'),
        ),
        migrations.CreateModel(
            name='CostumeMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.costume', verbose_name='Костюм')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.material', verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Материал костюма',
                'verbose_name_plural': 'Материалы костюмов',
                'db_table': 'costume_material',
                'unique_together': {('costume', 'material')},
            },
        ),
        migrations.AddField(
            model_name='costume',
            name='materials',
            field=models.ManyToManyField(related_name='costumes', through='catalogue.CostumeMaterial', to='catalogue.material', verbose_name='Материалы'),
        ),
        migrations.AddField(
            model_name='material',
            name='classification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='catalogue.materialclassification', verbose_name='Классификация материала'),
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата заявки')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='Время заявки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='catalogue.renter', verbose_name='Арендатор')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'db_table': 'request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('costume', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.costume', verbose_name='Костюм')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalogue.request', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Элемент заявки',
                'verbose_name_plural': 'Элементы заявок',
                'db_table': 'request_item',
            },
        ),
        migrations.AddField(
            model_name='request',
            name='costumes',
            field=models.ManyToManyField(related_name='requests', through='catalogue.RequestItem', to='catalogue.costume', verbose_name='Костюмы'),
        ),
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='catalogue.requeststatus', verbose_name='Статус заявки'),
        ),
        migrations.AddField(
            model_name='costume',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='costumes', to='catalogue.season', verbose_name='Сезон'),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=256, verbose_name='Тема заявки в поддержку')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновленена')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='catalogue.renter', verbose_name='От кого заявка')),
                ('support', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='catalogue.grantperson', verbose_name='Кто работает с заявкой')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='catalogue.ticketstatus', verbose_name='Статус заявки поддеркжи')),
            ],
            options={
                'verbose_name': 'Заявка в поддержку',
                'verbose_name_plural': 'Заявки в поддержку',
                'db_table': 'ticket',
                'ordering': ['status'],
            },
        ),
        migrations.CreateModel(
            name='TicketMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField(max_length=1024, verbose_name='Сообщение')),
                ('from_msg', models.CharField(max_length=36, verbose_name='Уникальный номер отправителя')),
                ('to_msg', models.CharField(max_length=36, verbose_name='Уникальный номер получателя')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Отправлено')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_msgs', to='catalogue.ticket', verbose_name='Заявка в поддержку')),
            ],
            options={
                'verbose_name': 'Сообщение в заявке',
                'verbose_name_plural': 'Сообщения в заявке',
                'db_table': 'ticket_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(default=catalogue.models.first_available_date_for_rent, verbose_name='Дата начала аренды')),
                ('time_start', models.TimeField(default=catalogue.models.time_now, verbose_name='Время начала аренды')),
                ('date_end', models.DateField(verbose_name='Дата окончания аренды')),
                ('time_end', models.TimeField(verbose_name='Время окончания аренды')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rents', to='catalogue.rentstatus', verbose_name='Статус аренды')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='rent', to='catalogue.request', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Аренда',
                'verbose_name_plural': 'Аренды',
                'db_table': 'rent',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('date_end__gte', models.F('date_start'))), name='end_date_after_start_date')],
            },
        ),
        migrations.AddConstraint(
            model_name='requestitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='quantity_positive'),
        ),
        migrations.AlterUniqueTogether(
            name='requestitem',
            unique_together={('costume', 'request')},
        ),
        migrations.AddConstraint(
            model_name='costume',
            constraint=models.CheckConstraint(condition=models.Q(('count__gte', 0)), name='count_non_negative'),
        ),
    ]
