# Generated by Django 6.0.2 on 2026-05-23 05:55

import catalogue.encryption
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_remove_ticketmessages_from_msg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmessages',
            name='sender_id',
            field=models.PositiveIntegerField(default=0, verbose_name='Код отправителя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grantperson',
            name='email',
            field=catalogue.encryption.EncryptedCharField(blank=True, max_length=2286, null=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='grantperson',
            name='first_name',
            field=catalogue.encryption.EncryptedCharField(max_length=900, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='grantperson',
            name='last_name',
            field=catalogue.encryption.EncryptedCharField(max_length=900, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='grantperson',
            name='middle_name',
            field=catalogue.encryption.EncryptedCharField(blank=True, max_length=900, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='grantperson',
            name='phone_number',
            field=catalogue.encryption.EncryptedCharField(blank=True, max_length=450, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='email',
            field=catalogue.encryption.EncryptedCharField(blank=True, max_length=2286, null=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='first_name',
            field=catalogue.encryption.EncryptedCharField(max_length=900, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='last_name',
            field=catalogue.encryption.EncryptedCharField(max_length=900, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='middle_name',
            field=catalogue.encryption.EncryptedCharField(blank=True, max_length=900, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='phone_number',
            field=catalogue.encryption.EncryptedCharField(blank=True, max_length=450, null=True, verbose_name='Номер телефона'),
        ),
        migrations.CreateModel(
            name='MediaTicketMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.ImageField(upload_to='messages_photo/%Y/%m/', verbose_name='Приложенные изображения в сообщении')),
                ('ticket_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='catalogue.ticketmessages', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Медиа в сообщении',
                'verbose_name_plural': 'Медиа в сообщении',
                'db_table': 'ticket_messages_medias',
            },
        ),
    ]
