# Generated by Django 6.0.2 on 2026-05-23 08:10

import catalogue.encryption
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_ticketmessages_sender_id_alter_grantperson_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grantperson',
            name='email',
            field=catalogue.encryption.EncryptedCharField(blank=True, max_length=2286, null=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='grantperson',
            name='first_name',
            field=catalogue.encryption.EncryptedCharField(max_length=900, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='grantperson',
            name='last_name',
            field=catalogue.encryption.EncryptedCharField(max_length=900, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='grantperson',
            name='middle_name',
            field=catalogue.encryption.EncryptedCharField(blank=True, max_length=900, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='grantperson',
            name='phone_number',
            field=catalogue.encryption.EncryptedCharField(blank=True, max_length=450, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='email',
            field=catalogue.encryption.EncryptedCharField(blank=True, max_length=2286, null=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='first_name',
            field=catalogue.encryption.EncryptedCharField(max_length=900, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='last_name',
            field=catalogue.encryption.EncryptedCharField(max_length=900, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='middle_name',
            field=catalogue.encryption.EncryptedCharField(blank=True, max_length=900, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='phone_number',
            field=catalogue.encryption.EncryptedCharField(blank=True, max_length=450, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='ticketmessages',
            name='sender_id',
            field=models.CharField(max_length=36, verbose_name='Код отправителя'),
        ),
    ]
